---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: monk-blue
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: akmods
    # base: asus # if not specified, classic "main" base is used by default
    install: []
    nvidia-driver: nvidia-open

  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: gnome-extensions
    install:
      - 1160  # Dash to Panel
      - 2932  # Executor
      - 4839  # Clipboard History
      - 517   # Caffeine
      - 2236  # Night Theme Switcher
      - 615   # AppIndicator and KStatusNotifierItem Support
      - 9875  # O-tiling
      - 4998  # Legacy (GTK3) Theme Scheme Auto Switcher
      - 1401  # Bluetooth Quick Connect
      - 3193  # Blur my Shell
      - 10046 # Custom Touchpad Gestures

  - type: dnf
    repos:
      keys:
        - "https://pkgs.tailscale.com/stable/fedora/repo.gpg"
      files:
        - "https://pkgs.tailscale.com/stable/fedora/tailscale.repo"
      nonfree: rpmfusion
      copr:
        - atim/starship
        - binlab/vscode
        - bieszczaders/kernel-cachyos-addons
        - itotm/cachyos-kernel-znver4 # used to overlay cachy-os kernel if needed
    install:
      packages:
        - micro
        - starship
        # cachy os
        - ananicy-cpp
        # utilities
        - pam-u2f
        - pamu2fcfg
        - power-profiles-daemon
        - powertop
        - zsh
        - git
        - git-lfs
        - btop
        - zoxide
        - fzf
        - sysbench
        - tmux
        - btop
        - s-tui
        - tailscale # make sure repo is added above
        - vscode
    remove:
      packages:
        # example: removing firefox (in favor of the flatpak)
        # "firefox" is the main package, "firefox-langpacks" is a dependency
        - firefox
        - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)
        - tuned-ppd

  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default
        install: # system flatpaks we want all users to have and not remove
          - be.alexandervanhee.gradia
          - com.github.PintaProject.Pinta
          - com.github.tchx84.Flatseal
          - com.google.Chrome
          - com.mattjakeman.ExtensionManager
          - com.moonlight_stream.Moonlight
          - com.ranfdev.DistroShelf
          - com.sublimehq.SublimeText
          - dev.deedles.Trayscale
          - net.cozic.joplin_desktop
          - net.nokyan.Resources
          - org.gnome.Calculator
          - org.gnome.Calendar
          - org.gnome.Characters
          - org.gnome.clocks
          - org.gnome.Connections
          - org.gnome.Extensions
          - org.gnome.FileRoller
          - org.gnome.Firmware
          - org.gnome.font-viewer
          - org.gnome.Logs
          - org.gnome.Loupe
          - org.gnome.NautilusPreviewer
          - org.gnome.Papers
          - org.gnome.SimpleScan
          - org.gnome.Snapshot
          - org.gnome.Weather
          - page.tesk.Refine
      - scope: user # Also add Flathub user repo, but no user packages

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
